location /livepreview {
    alias /var/www/geocaching/livepreview/public;

    gzip on;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml image/jpeg image/png image/gif image/webp;
    gzip_min_length 1000;
    gzip_vary on;

    try_files $uri $uri/ =404;
}
